/*
 * Copyright (c) 2026 Eitanity Systems VCC. All rights reserved.
 * Use of this source code is governed by the BSD-2-Clause licence in LICENSE.
 *
 * Writes a Go file of the code points glibc's iswprint accepts
 * in a UTF-8 locale, with the columns file(1) counts for each. file prints a
 * name or an answer through mbrtowc and iswprint, and pads names by
 * wcwidth, so these tables are what decides which characters it escapes
 * and how wide a name is. A printable character counts wcwidth's columns,
 * or one when wcwidth says zero, as file_mbswidth counts it.
 *
 * Usage: wctype PACKAGE > wctype.go   (make wctype runs it)
 */
#define _XOPEN_SOURCE 700
#include <gnu/libc-version.h>
#include <locale.h>
#include <stdio.h>
#include <wchar.h>
#include <wctype.h>

#define LOCALE "C.UTF-8"
#define MAXCODE 0x10FFFFu

/* columns is what file counts for c: 0 when it is escaped. */
static int
columns(unsigned c)
{
	int w;

	if (c >= 0xD800 && c <= 0xDFFF)
		return -1; /* never decoded from UTF-8: not part of any run */
	if (!iswprint((wint_t)c))
		return 0;
	w = wcwidth((wchar_t)c);
	return w > 0 ? w : 1;
}

int
main(int argc, char **argv)
{
	unsigned c, start = 0, last = 0;
	int cur = 0, w;

	if (argc != 2) {
		fprintf(stderr, "usage: wctype PACKAGE\n");
		return 2;
	}
	if (setlocale(LC_CTYPE, LOCALE) == NULL) {
		fprintf(stderr, "wctype: no %s locale\n", LOCALE);
		return 1;
	}
	printf("// Code generated by scripts/wctype.c from glibc %s, locale %s. DO NOT EDIT.\n\n",
	    gnu_get_libc_version(), LOCALE);
	printf("package %s\n\n", argv[1]);
	printf("// printRanges are the runs of code points glibc's iswprint accepts in a\n");
	printf("// UTF-8 locale, in order, each with the columns file counts for it.\n");
	printf("var printRanges = [...]printRange{\n");
	for (c = 0; c <= MAXCODE; c++) {
		w = columns(c);
		if (w < 0)
			continue; /* surrogates sit between runs */
		if (w == cur && c == last + 1) {
			last = c;
			continue;
		}
		if (cur > 0)
			printf("\t{0x%x, 0x%x, %d},\n", start, last, cur);
		cur = w;
		start = last = c;
	}
	if (cur > 0)
		printf("\t{0x%x, 0x%x, %d},\n", start, last, cur);
	printf("}\n");
	return 0;
}
